// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Role struct {
	Level       int32
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID          int32
	Username    string
	Email       string
	PhoneNumber string
	Address     string
	Dob         pgtype.Date
	Password    string
	Fullname    string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Role        int32
}

type UserSession struct {
	ID                    int32
	UserID                int32
	ActiveToken           string
	RefreshToken          string
	ActiveTokenExpiresAt  pgtype.Timestamp
	RefreshTokenExpiresAt pgtype.Timestamp
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}
