// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: role.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRoleByLevel = `-- name: GetRoleByLevel :one
SELECT level, name, description FROM roles WHERE level = $1
`

type GetRoleByLevelRow struct {
	Level       int32
	Name        string
	Description pgtype.Text
}

func (q *Queries) GetRoleByLevel(ctx context.Context, level int32) (GetRoleByLevelRow, error) {
	row := q.db.QueryRow(ctx, getRoleByLevel, level)
	var i GetRoleByLevelRow
	err := row.Scan(&i.Level, &i.Name, &i.Description)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT level, name, description FROM roles WHERE name = $1
`

type GetRoleByNameRow struct {
	Level       int32
	Name        string
	Description pgtype.Text
}

func (q *Queries) GetRoleByName(ctx context.Context, name string) (GetRoleByNameRow, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i GetRoleByNameRow
	err := row.Scan(&i.Level, &i.Name, &i.Description)
	return i, err
}
