// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, phone_number, address, dob, password, fullname, role, created_at, updated_at FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID          int32
	Username    string
	Email       string
	PhoneNumber string
	Address     string
	Dob         pgtype.Date
	Password    string
	Fullname    string
	Role        int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.Dob,
		&i.Password,
		&i.Fullname,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, phone_number, address, dob, password, fullname, role, created_at, updated_at FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID          int32
	Username    string
	Email       string
	PhoneNumber string
	Address     string
	Dob         pgtype.Date
	Password    string
	Fullname    string
	Role        int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.Dob,
		&i.Password,
		&i.Fullname,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, phone_number, address, dob, password, fullname, role, created_at, updated_at FROM users WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID          int32
	Username    string
	Email       string
	PhoneNumber string
	Address     string
	Dob         pgtype.Date
	Password    string
	Fullname    string
	Role        int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.Dob,
		&i.Password,
		&i.Fullname,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (username, email, phone_number, address, dob, password, fullname, role) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id
`

type InsertUserParams struct {
	Username    string
	Email       string
	PhoneNumber string
	Address     string
	Dob         pgtype.Date
	Password    string
	Fullname    string
	Role        int32
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Username,
		arg.Email,
		arg.PhoneNumber,
		arg.Address,
		arg.Dob,
		arg.Password,
		arg.Fullname,
		arg.Role,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
